{
  "openapi": "3.0.0",
  "info": {
    "title": "chat-API",
    "contact": {},
    "version": "1.0"
  },

  "paths": {
    "/api/v1/users": {
      "post": {
        "tags": ["users"],
        "summary": "register",
        "operationId": "register",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/registerrequest"
                  },
                  {
                    "example": {
                      "firstname": "Cane",
                      "lastname": "Anderson",
                      "email": "cane@gmail.com",
                      "password": "1234567@Aa"
                    }
                  }
                ]
              },
              "example": {
                "firstname": "Cane",
                "lastname": "Anderson",
                "email": "cane@gmail.com",
                "password": "1234567@Aa"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "get": {
        "tags": ["users"],
        "summary": "get all Users",
        "operationId": "getallUsers",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/v1/users/login": {
      "post": {
        "tags": ["users"],
        "summary": "login",
        "operationId": "login",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/loginrequest"
                  },
                  {
                    "example": {
                      "email": "olleyv100@gmail.com",
                      "password": "1234567@Aa"
                    }
                  }
                ]
              },
              "example": {
                "email": "olleyv100@gmail.com",
                "password": "1234567@Aa"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/v1/conversations": {
      "post": {
        "security": [
          {
            "bearer": []
          }
        ],
        "tags": ["conversations"],
        "summary": "create conversation",
        "operationId": "createconversation",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/createconversationrequest"
                  },
                  {
                    "example": {
                      "userId": 1,
                      "participantId": 2
                    }
                  }
                ]
              },
              "example": {
                "userId": 1,
                "participantId": 2
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/v1/conversations/group": {
      "post": {
        "security": [
          {
            "bearer": []
          }
        ],
        "tags": ["conversations"],
        "summary": "create group conversation",
        "operationId": "creategroupconversation",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/creategroupconversationrequest"
                  },
                  {
                    "example": {
                      "userId": 1,
                      "participantsIds": [2, 3],
                      "title": "Primer chat grupal"
                    }
                  }
                ]
              },
              "example": {
                "userId": 1,
                "participantsIds": [2, 3],
                "title": "Primer chat grupal"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/v1/conversations/{id}": {
      "post": {
        "security": [
          {
            "bearer": []
          }
        ],
        "get": {
          "tags": ["conversations"],
          "summary": "get all conversations by user",
          "operationId": "getallconversationsbyuser",
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "integer",
                "format": "int32",
                "example": 1
              }
            }
          ],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/api/v1/messages/conversation/{id}": {
        "post": {
          "tags": ["messages"],
          "summary": "create new message",
          "operationId": "createnewmessage",
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "integer",
                "format": "int32",
                "example": 15
              }
            }
          ],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/createnewmessagerequest"
                    },
                    {
                      "example": {
                        "content": "Hola, soy Cane ",
                        "senderId": 3
                      }
                    }
                  ]
                },
                "example": {
                  "content": "Hola, soy Cane ",
                  "senderId": 3
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        },
        "get": {
          "tags": ["messages"],
          "summary": "get conversation messages",
          "operationId": "getconversationmessages",
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "integer",
                "format": "int32",
                "example": 15
              }
            }
          ],
          "responses": {
            "200": {
              "description": "",
              "headers": {}
            }
          },
          "deprecated": false,
          "security": [
            {
              "bearer": []
            }
          ]
        }
      }
    },
    "components": {
      "schemas": {
        "registerrequest": {
          "title": "registerrequest",
          "required": ["firstname", "lastname", "email", "password"],
          "type": "object",
          "properties": {
            "firstname": {
              "type": "string"
            },
            "lastname": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "password": {
              "type": "string"
            }
          },
          "example": {
            "firstname": "Cane",
            "lastname": "Anderson",
            "email": "cane@gmail.com",
            "password": "1234567@Aa"
          }
        },
        "loginrequest": {
          "title": "loginrequest",
          "required": ["email", "password"],
          "type": "object",
          "properties": {
            "email": {
              "type": "string"
            },
            "password": {
              "type": "string"
            }
          },
          "example": {
            "email": "olleyv100@gmail.com",
            "password": "1234567@Aa"
          }
        },
        "createconversationrequest": {
          "title": "createconversationrequest",
          "required": ["userId", "participantId"],
          "type": "object",
          "properties": {
            "userId": {
              "type": "integer",
              "format": "int32"
            },
            "participantId": {
              "type": "integer",
              "format": "int32"
            }
          },
          "example": {
            "userId": 1,
            "participantId": 2
          }
        },
        "creategroupconversationrequest": {
          "title": "creategroupconversationrequest",
          "required": ["userId", "participantsIds", "title"],
          "type": "object",
          "properties": {
            "userId": {
              "type": "integer",
              "format": "int32"
            },
            "participantsIds": {
              "type": "array",
              "items": {
                "type": "integer",
                "format": "int32"
              },
              "description": ""
            },
            "title": {
              "type": "string"
            }
          },
          "example": {
            "userId": 1,
            "participantsIds": [2, 3],
            "title": "Primer chat grupal"
          }
        },
        "createnewmessagerequest": {
          "title": "createnewmessagerequest",
          "required": ["content", "senderId"],
          "type": "object",
          "properties": {
            "content": {
              "type": "string"
            },
            "senderId": {
              "type": "integer",
              "format": "int32"
            }
          },
          "example": {
            "content": "Hola, soy Cane ",
            "senderId": 3
          }
        }
      },
      "securitySchemes": {
        "bearer": {
          "type": "http",
          "scheme": "bearer"
        }
      }
    },
    "security": [],
    "tags": [
      {
        "name": "users"
      },
      {
        "name": "conversations"
      },
      {
        "name": "messages"
      }
    ]
  }
}
